"""Makes src/font_big.c: Montserrat Medium, digits and '-' '.' only, at a size
LVGL's bundled fonts stop short of (they end at 48 px).

  tools/case/.venv/bin/python tools/gen_big_font.py [size]

Needs the LVGL copy PlatformIO downloads (run `pio run` once). Output is a
plain 4 bpp LVGL font, the same layout lv_font_conv writes, without kerning.
"""

import pathlib
import sys

from PIL import Image, ImageDraw, ImageFont

SIZE = int(sys.argv[1]) if len(sys.argv) > 1 else 64
FIRST, LAST = 0x2D, 0x39   # '-' '.' '/' '0'..'9'

root = pathlib.Path(__file__).resolve().parents[1]
ttf = root / ".pio/libdeps/outback_gauge/lvgl/scripts/built_in_font/Montserrat-Medium.ttf"
font = ImageFont.truetype(str(ttf), SIZE)
ascent, descent = font.getmetrics()

# LVGL packs the bitmap continuously, with no padding at the end of each row.
bitmap = []
glyphs = []
for code in range(FIRST, LAST + 1):
    ch = chr(code)
    l, t, r, b = font.getbbox(ch, anchor="ls")
    w, h = max(r - l, 0), max(b - t, 0)
    index = (len(bitmap))
    if w and h:
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-l, -t), ch, font=font, fill=255, anchor="ls")
        nibbles = [v >> 4 for v in img.getdata()]
        if len(nibbles) % 2:
            nibbles.append(0)
        bitmap += [(nibbles[i] << 4) | nibbles[i + 1] for i in range(0, len(nibbles), 2)]
    glyphs.append((index, round(font.getlength(ch) * 16), w, h, l, -b))

out = [f'''/* Generated by tools/gen_big_font.py: Montserrat Medium {SIZE} px, 4 bpp, U+{FIRST:04X}-U+{LAST:04X}. */
#include <lvgl.h>

static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{''']
for i in range(0, len(bitmap), 16):
    out.append("    " + ", ".join(f"0x{v:02x}" for v in bitmap[i:i + 16]) + ",")
out.append("};\n\nstatic const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {")
out.append("    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */,")
for index, adv, w, h, ox, oy in glyphs:
    out.append(f"    {{.bitmap_index = {index}, .adv_w = {adv}, .box_w = {w}, .box_h = {h}, .ofs_x = {ox}, .ofs_y = {oy}}},")
out.append(f'''}};

static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = {FIRST}, .range_length = {LAST - FIRST + 1}, .glyph_id_start = 1,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }}
}};

static lv_font_fmt_txt_glyph_cache_t cache;
static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 4,
    .kern_classes = 0,
    .bitmap_format = 0,
    .cache = &cache
}};

const lv_font_t font_big = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {ascent + descent},
    .base_line = {descent},
    .subpx = LV_FONT_SUBPX_NONE,
    .underline_position = -1,
    .underline_thickness = 1,
    .dsc = &font_dsc
}};
''')
(root / "src/font_big.c").write_text("\n".join(out))
print(f"wrote src/font_big.c: {len(bitmap)} bitmap bytes, line height {ascent + descent}")
